apiVersion: v1
kind: Pod
metadata:
  name: config-demo
  labels:
    app: config-demo
spec:
  containers:
  - name: alpine
    image: alpine:3.21
    command: ['sleep', '3600']
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: log_level
    - name: GREETING
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: greeting
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
      readOnly: true
    - name: secret-volume
      mountPath: /etc/secret
      readOnly: true
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  - name: secret-volume
    secret:
      secretName: db-secret