apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
  labels:
    app: pvc-demo
spec:
  containers:
  - name: alpine
    image: alpine:3.21
    command: ['sleep', '3600']
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-pvc